//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaminationMaterial
    {
        public int LaminationMaterialId { get; set; }
        public string OrderNoId { get; set; }
        public string OrderNo { get; set; }
        public string ArticleNo { get; set; }
        public string ShoeName { get; set; }
        public string PatternNo { get; set; }
        public string ProductNoList { get; set; }
        public string Position { get; set; }
        public string MaterialPart { get; set; }
        public string MaterialName { get; set; }
        public string Unit { get; set; }
        public Nullable<int> POQuantity { get; set; }
        public Nullable<int> SendQuantity { get; set; }
        public string DeliveryDate { get; set; }
        public string PurchaseDate { get; set; }
        public string SupplierName { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    }
}
