//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public int MachineId { get; set; }
        public Nullable<int> Number { get; set; }
        public string MachineType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Barcode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
