//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControl
    {
        public int Number { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> AccessTime { get; set; }
        public string FromDevice { get; set; }
    }
}
