//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ScissorsManagmentEntities : DbContext
    {
        public ScissorsManagmentEntities()
            : base("name=ScissorsManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<InspectionList> InspectionLists { get; set; }
        public DbSet<IssuanceList> IssuanceLists { get; set; }
        public DbSet<ScissorsList> ScissorsLists { get; set; }
        public DbSet<UserList> UserLists { get; set; }
    
        public virtual ObjectResult<spm_SelectUserList_Result> spm_SelectUserList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spm_SelectUserList_Result>("spm_SelectUserList");
        }
    }
}
