//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScissorsList
    {
        public int ScissorsId { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> IsBig { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    }
}
