//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuanceList
    {
        public int IssuanceId { get; set; }
        public string WorkerId { get; set; }
        public string Section { get; set; }
        public string Line { get; set; }
        public string ScissorsBarcode { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public string ScissorsBarcodeReplace { get; set; }
        public Nullable<System.DateTime> ReplaceTime { get; set; }
        public string IssuanceBy { get; set; }
        public Nullable<System.DateTime> IssuanceTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
    }
}
