//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebsiteTesting.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SampleRoomEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SampleRoomEntities object using the connection string found in the 'SampleRoomEntities' section of the application configuration file.
        /// </summary>
        public SampleRoomEntities() : base("name=SampleRoomEntities", "SampleRoomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleRoomEntities object.
        /// </summary>
        public SampleRoomEntities(string connectionString) : base(connectionString, "SampleRoomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleRoomEntities object.
        /// </summary>
        public SampleRoomEntities(EntityConnection connection) : base(connection, "SampleRoomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BorrowSho> BorrowShoes
        {
            get
            {
                if ((_BorrowShoes == null))
                {
                    _BorrowShoes = base.CreateObjectSet<BorrowSho>("BorrowShoes");
                }
                return _BorrowShoes;
            }
        }
        private ObjectSet<BorrowSho> _BorrowShoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SampleSho> SampleShoes
        {
            get
            {
                if ((_SampleShoes == null))
                {
                    _SampleShoes = base.CreateObjectSet<SampleSho>("SampleShoes");
                }
                return _SampleShoes;
            }
        }
        private ObjectSet<SampleSho> _SampleShoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemConfig> SystemConfigs
        {
            get
            {
                if ((_SystemConfigs == null))
                {
                    _SystemConfigs = base.CreateObjectSet<SystemConfig>("SystemConfigs");
                }
                return _SystemConfigs;
            }
        }
        private ObjectSet<SystemConfig> _SystemConfigs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BorrowShoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBorrowShoes(BorrowSho borrowSho)
        {
            base.AddObject("BorrowShoes", borrowSho);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SampleShoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSampleShoes(SampleSho sampleSho)
        {
            base.AddObject("SampleShoes", sampleSho);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemConfigs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemConfigs(SystemConfig systemConfig)
        {
            base.AddObject("SystemConfigs", systemConfig);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="article">No Metadata Documentation available.</param>
        /// <param name="rDNumber">No Metadata Documentation available.</param>
        /// <param name="articleName">No Metadata Documentation available.</param>
        /// <param name="color">No Metadata Documentation available.</param>
        /// <param name="shoelastCode">No Metadata Documentation available.</param>
        /// <param name="season">No Metadata Documentation available.</param>
        /// <param name="customer">No Metadata Documentation available.</param>
        /// <param name="size">No Metadata Documentation available.</param>
        /// <param name="factory">No Metadata Documentation available.</param>
        /// <param name="location">No Metadata Documentation available.</param>
        /// <param name="imagePath">No Metadata Documentation available.</param>
        /// <param name="quantity">No Metadata Documentation available.</param>
        /// <param name="modifiedTime">No Metadata Documentation available.</param>
        public int InsertSampleShoes_1(global::System.String article, global::System.String rDNumber, global::System.String articleName, global::System.String color, global::System.String shoelastCode, global::System.String season, global::System.String customer, global::System.String size, global::System.String factory, global::System.String location, global::System.String imagePath, Nullable<global::System.Int32> quantity, Nullable<global::System.DateTime> modifiedTime)
        {
            ObjectParameter articleParameter;
            if (article != null)
            {
                articleParameter = new ObjectParameter("Article", article);
            }
            else
            {
                articleParameter = new ObjectParameter("Article", typeof(global::System.String));
            }
    
            ObjectParameter rDNumberParameter;
            if (rDNumber != null)
            {
                rDNumberParameter = new ObjectParameter("RDNumber", rDNumber);
            }
            else
            {
                rDNumberParameter = new ObjectParameter("RDNumber", typeof(global::System.String));
            }
    
            ObjectParameter articleNameParameter;
            if (articleName != null)
            {
                articleNameParameter = new ObjectParameter("ArticleName", articleName);
            }
            else
            {
                articleNameParameter = new ObjectParameter("ArticleName", typeof(global::System.String));
            }
    
            ObjectParameter colorParameter;
            if (color != null)
            {
                colorParameter = new ObjectParameter("Color", color);
            }
            else
            {
                colorParameter = new ObjectParameter("Color", typeof(global::System.String));
            }
    
            ObjectParameter shoelastCodeParameter;
            if (shoelastCode != null)
            {
                shoelastCodeParameter = new ObjectParameter("ShoelastCode", shoelastCode);
            }
            else
            {
                shoelastCodeParameter = new ObjectParameter("ShoelastCode", typeof(global::System.String));
            }
    
            ObjectParameter seasonParameter;
            if (season != null)
            {
                seasonParameter = new ObjectParameter("Season", season);
            }
            else
            {
                seasonParameter = new ObjectParameter("Season", typeof(global::System.String));
            }
    
            ObjectParameter customerParameter;
            if (customer != null)
            {
                customerParameter = new ObjectParameter("Customer", customer);
            }
            else
            {
                customerParameter = new ObjectParameter("Customer", typeof(global::System.String));
            }
    
            ObjectParameter sizeParameter;
            if (size != null)
            {
                sizeParameter = new ObjectParameter("Size", size);
            }
            else
            {
                sizeParameter = new ObjectParameter("Size", typeof(global::System.String));
            }
    
            ObjectParameter factoryParameter;
            if (factory != null)
            {
                factoryParameter = new ObjectParameter("Factory", factory);
            }
            else
            {
                factoryParameter = new ObjectParameter("Factory", typeof(global::System.String));
            }
    
            ObjectParameter locationParameter;
            if (location != null)
            {
                locationParameter = new ObjectParameter("Location", location);
            }
            else
            {
                locationParameter = new ObjectParameter("Location", typeof(global::System.String));
            }
    
            ObjectParameter imagePathParameter;
            if (imagePath != null)
            {
                imagePathParameter = new ObjectParameter("ImagePath", imagePath);
            }
            else
            {
                imagePathParameter = new ObjectParameter("ImagePath", typeof(global::System.String));
            }
    
            ObjectParameter quantityParameter;
            if (quantity.HasValue)
            {
                quantityParameter = new ObjectParameter("Quantity", quantity);
            }
            else
            {
                quantityParameter = new ObjectParameter("Quantity", typeof(global::System.Int32));
            }
    
            ObjectParameter modifiedTimeParameter;
            if (modifiedTime.HasValue)
            {
                modifiedTimeParameter = new ObjectParameter("ModifiedTime", modifiedTime);
            }
            else
            {
                modifiedTimeParameter = new ObjectParameter("ModifiedTime", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction("InsertSampleShoes_1", articleParameter, rDNumberParameter, articleNameParameter, colorParameter, shoelastCodeParameter, seasonParameter, customerParameter, sizeParameter, factoryParameter, locationParameter, imagePathParameter, quantityParameter, modifiedTimeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="article">No Metadata Documentation available.</param>
        public ObjectResult<SelectShoesImageByArticle_Result> SelectShoesImageByArticle(global::System.String article)
        {
            ObjectParameter articleParameter;
            if (article != null)
            {
                articleParameter = new ObjectParameter("Article", article);
            }
            else
            {
                articleParameter = new ObjectParameter("Article", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<SelectShoesImageByArticle_Result>("SelectShoesImageByArticle", articleParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="article">No Metadata Documentation available.</param>
        /// <param name="rDNumber">No Metadata Documentation available.</param>
        /// <param name="articleName">No Metadata Documentation available.</param>
        /// <param name="color">No Metadata Documentation available.</param>
        /// <param name="shoelastCode">No Metadata Documentation available.</param>
        /// <param name="season">No Metadata Documentation available.</param>
        /// <param name="customer">No Metadata Documentation available.</param>
        /// <param name="size">No Metadata Documentation available.</param>
        /// <param name="factory">No Metadata Documentation available.</param>
        /// <param name="location">No Metadata Documentation available.</param>
        /// <param name="quantity">No Metadata Documentation available.</param>
        /// <param name="modifiedTime">No Metadata Documentation available.</param>
        public int UpdateSampleShoes_1(global::System.String article, global::System.String rDNumber, global::System.String articleName, global::System.String color, global::System.String shoelastCode, global::System.String season, global::System.String customer, global::System.String size, global::System.String factory, global::System.String location, Nullable<global::System.Int32> quantity, Nullable<global::System.DateTime> modifiedTime)
        {
            ObjectParameter articleParameter;
            if (article != null)
            {
                articleParameter = new ObjectParameter("Article", article);
            }
            else
            {
                articleParameter = new ObjectParameter("Article", typeof(global::System.String));
            }
    
            ObjectParameter rDNumberParameter;
            if (rDNumber != null)
            {
                rDNumberParameter = new ObjectParameter("RDNumber", rDNumber);
            }
            else
            {
                rDNumberParameter = new ObjectParameter("RDNumber", typeof(global::System.String));
            }
    
            ObjectParameter articleNameParameter;
            if (articleName != null)
            {
                articleNameParameter = new ObjectParameter("ArticleName", articleName);
            }
            else
            {
                articleNameParameter = new ObjectParameter("ArticleName", typeof(global::System.String));
            }
    
            ObjectParameter colorParameter;
            if (color != null)
            {
                colorParameter = new ObjectParameter("Color", color);
            }
            else
            {
                colorParameter = new ObjectParameter("Color", typeof(global::System.String));
            }
    
            ObjectParameter shoelastCodeParameter;
            if (shoelastCode != null)
            {
                shoelastCodeParameter = new ObjectParameter("ShoelastCode", shoelastCode);
            }
            else
            {
                shoelastCodeParameter = new ObjectParameter("ShoelastCode", typeof(global::System.String));
            }
    
            ObjectParameter seasonParameter;
            if (season != null)
            {
                seasonParameter = new ObjectParameter("Season", season);
            }
            else
            {
                seasonParameter = new ObjectParameter("Season", typeof(global::System.String));
            }
    
            ObjectParameter customerParameter;
            if (customer != null)
            {
                customerParameter = new ObjectParameter("Customer", customer);
            }
            else
            {
                customerParameter = new ObjectParameter("Customer", typeof(global::System.String));
            }
    
            ObjectParameter sizeParameter;
            if (size != null)
            {
                sizeParameter = new ObjectParameter("Size", size);
            }
            else
            {
                sizeParameter = new ObjectParameter("Size", typeof(global::System.String));
            }
    
            ObjectParameter factoryParameter;
            if (factory != null)
            {
                factoryParameter = new ObjectParameter("Factory", factory);
            }
            else
            {
                factoryParameter = new ObjectParameter("Factory", typeof(global::System.String));
            }
    
            ObjectParameter locationParameter;
            if (location != null)
            {
                locationParameter = new ObjectParameter("Location", location);
            }
            else
            {
                locationParameter = new ObjectParameter("Location", typeof(global::System.String));
            }
    
            ObjectParameter quantityParameter;
            if (quantity.HasValue)
            {
                quantityParameter = new ObjectParameter("Quantity", quantity);
            }
            else
            {
                quantityParameter = new ObjectParameter("Quantity", typeof(global::System.Int32));
            }
    
            ObjectParameter modifiedTimeParameter;
            if (modifiedTime.HasValue)
            {
                modifiedTimeParameter = new ObjectParameter("ModifiedTime", modifiedTime);
            }
            else
            {
                modifiedTimeParameter = new ObjectParameter("ModifiedTime", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction("UpdateSampleShoes_1", articleParameter, rDNumberParameter, articleNameParameter, colorParameter, shoelastCodeParameter, seasonParameter, customerParameter, sizeParameter, factoryParameter, locationParameter, quantityParameter, modifiedTimeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="article">No Metadata Documentation available.</param>
        /// <param name="image">No Metadata Documentation available.</param>
        public int UpdateShoesImage(global::System.String article, global::System.Byte[] image)
        {
            ObjectParameter articleParameter;
            if (article != null)
            {
                articleParameter = new ObjectParameter("Article", article);
            }
            else
            {
                articleParameter = new ObjectParameter("Article", typeof(global::System.String));
            }
    
            ObjectParameter imageParameter;
            if (image != null)
            {
                imageParameter = new ObjectParameter("Image", image);
            }
            else
            {
                imageParameter = new ObjectParameter("Image", typeof(global::System.Byte[]));
            }
    
            return base.ExecuteFunction("UpdateShoesImage", articleParameter, imageParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleRoomModel", Name="BorrowSho")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BorrowSho : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BorrowSho object.
        /// </summary>
        /// <param name="borrowShoesId">Initial value of the BorrowShoesId property.</param>
        public static BorrowSho CreateBorrowSho(global::System.Int32 borrowShoesId)
        {
            BorrowSho borrowSho = new BorrowSho();
            borrowSho.BorrowShoesId = borrowShoesId;
            return borrowSho;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BorrowShoesId
        {
            get
            {
                return _BorrowShoesId;
            }
            set
            {
                if (_BorrowShoesId != value)
                {
                    OnBorrowShoesIdChanging(value);
                    ReportPropertyChanging("BorrowShoesId");
                    _BorrowShoesId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BorrowShoesId");
                    OnBorrowShoesIdChanged();
                }
            }
        }
        private global::System.Int32 _BorrowShoesId;
        partial void OnBorrowShoesIdChanging(global::System.Int32 value);
        partial void OnBorrowShoesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                OnEmployeeIdChanging(value);
                ReportPropertyChanging("EmployeeId");
                _EmployeeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeId");
                OnEmployeeIdChanged();
            }
        }
        private global::System.String _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.String value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeName
        {
            get
            {
                return _EmployeeName;
            }
            set
            {
                OnEmployeeNameChanging(value);
                ReportPropertyChanging("EmployeeName");
                _EmployeeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeName");
                OnEmployeeNameChanged();
            }
        }
        private global::System.String _EmployeeName;
        partial void OnEmployeeNameChanging(global::System.String value);
        partial void OnEmployeeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeSection
        {
            get
            {
                return _EmployeeSection;
            }
            set
            {
                OnEmployeeSectionChanging(value);
                ReportPropertyChanging("EmployeeSection");
                _EmployeeSection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeSection");
                OnEmployeeSectionChanged();
            }
        }
        private global::System.String _EmployeeSection;
        partial void OnEmployeeSectionChanging(global::System.String value);
        partial void OnEmployeeSectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Article
        {
            get
            {
                return _Article;
            }
            set
            {
                OnArticleChanging(value);
                ReportPropertyChanging("Article");
                _Article = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Article");
                OnArticleChanged();
            }
        }
        private global::System.String _Article;
        partial void OnArticleChanging(global::System.String value);
        partial void OnArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeImagePath
        {
            get
            {
                return _EmployeeImagePath;
            }
            set
            {
                OnEmployeeImagePathChanging(value);
                ReportPropertyChanging("EmployeeImagePath");
                _EmployeeImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeImagePath");
                OnEmployeeImagePathChanged();
            }
        }
        private global::System.String _EmployeeImagePath;
        partial void OnEmployeeImagePathChanging(global::System.String value);
        partial void OnEmployeeImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeLine
        {
            get
            {
                return _EmployeeLine;
            }
            set
            {
                OnEmployeeLineChanging(value);
                ReportPropertyChanging("EmployeeLine");
                _EmployeeLine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeLine");
                OnEmployeeLineChanged();
            }
        }
        private global::System.String _EmployeeLine;
        partial void OnEmployeeLineChanging(global::System.String value);
        partial void OnEmployeeLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BorrowTime
        {
            get
            {
                return _BorrowTime;
            }
            set
            {
                OnBorrowTimeChanging(value);
                ReportPropertyChanging("BorrowTime");
                _BorrowTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BorrowTime");
                OnBorrowTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _BorrowTime;
        partial void OnBorrowTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnBorrowTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PayTime
        {
            get
            {
                return _PayTime;
            }
            set
            {
                OnPayTimeChanging(value);
                ReportPropertyChanging("PayTime");
                _PayTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayTime");
                OnPayTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PayTime;
        partial void OnPayTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPayTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleRoomModel", Name="SampleSho")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SampleSho : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SampleSho object.
        /// </summary>
        /// <param name="article">Initial value of the Article property.</param>
        public static SampleSho CreateSampleSho(global::System.String article)
        {
            SampleSho sampleSho = new SampleSho();
            sampleSho.Article = article;
            return sampleSho;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Article
        {
            get
            {
                return _Article;
            }
            set
            {
                if (_Article != value)
                {
                    OnArticleChanging(value);
                    ReportPropertyChanging("Article");
                    _Article = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Article");
                    OnArticleChanged();
                }
            }
        }
        private global::System.String _Article;
        partial void OnArticleChanging(global::System.String value);
        partial void OnArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RDNumber
        {
            get
            {
                return _RDNumber;
            }
            set
            {
                OnRDNumberChanging(value);
                ReportPropertyChanging("RDNumber");
                _RDNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RDNumber");
                OnRDNumberChanged();
            }
        }
        private global::System.String _RDNumber;
        partial void OnRDNumberChanging(global::System.String value);
        partial void OnRDNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleName
        {
            get
            {
                return _ArticleName;
            }
            set
            {
                OnArticleNameChanging(value);
                ReportPropertyChanging("ArticleName");
                _ArticleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleName");
                OnArticleNameChanged();
            }
        }
        private global::System.String _ArticleName;
        partial void OnArticleNameChanging(global::System.String value);
        partial void OnArticleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShoelastCode
        {
            get
            {
                return _ShoelastCode;
            }
            set
            {
                OnShoelastCodeChanging(value);
                ReportPropertyChanging("ShoelastCode");
                _ShoelastCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShoelastCode");
                OnShoelastCodeChanged();
            }
        }
        private global::System.String _ShoelastCode;
        partial void OnShoelastCodeChanging(global::System.String value);
        partial void OnShoelastCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Season
        {
            get
            {
                return _Season;
            }
            set
            {
                OnSeasonChanging(value);
                ReportPropertyChanging("Season");
                _Season = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Season");
                OnSeasonChanged();
            }
        }
        private global::System.String _Season;
        partial void OnSeasonChanging(global::System.String value);
        partial void OnSeasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Customer
        {
            get
            {
                return _Customer;
            }
            set
            {
                OnCustomerChanging(value);
                ReportPropertyChanging("Customer");
                _Customer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Customer");
                OnCustomerChanged();
            }
        }
        private global::System.String _Customer;
        partial void OnCustomerChanging(global::System.String value);
        partial void OnCustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Factory
        {
            get
            {
                return _Factory;
            }
            set
            {
                OnFactoryChanging(value);
                ReportPropertyChanging("Factory");
                _Factory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Factory");
                OnFactoryChanged();
            }
        }
        private global::System.String _Factory;
        partial void OnFactoryChanging(global::System.String value);
        partial void OnFactoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedTime
        {
            get
            {
                return _ModifiedTime;
            }
            set
            {
                OnModifiedTimeChanging(value);
                ReportPropertyChanging("ModifiedTime");
                _ModifiedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedTime");
                OnModifiedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedTime;
        partial void OnModifiedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleRoomModel", Name="SystemConfig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemConfig : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemConfig object.
        /// </summary>
        /// <param name="cabinetCount">Initial value of the CabinetCount property.</param>
        /// <param name="rackCount">Initial value of the RackCount property.</param>
        public static SystemConfig CreateSystemConfig(global::System.Int32 cabinetCount, global::System.Int32 rackCount)
        {
            SystemConfig systemConfig = new SystemConfig();
            systemConfig.CabinetCount = cabinetCount;
            systemConfig.RackCount = rackCount;
            return systemConfig;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CabinetCount
        {
            get
            {
                return _CabinetCount;
            }
            set
            {
                if (_CabinetCount != value)
                {
                    OnCabinetCountChanging(value);
                    ReportPropertyChanging("CabinetCount");
                    _CabinetCount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CabinetCount");
                    OnCabinetCountChanged();
                }
            }
        }
        private global::System.Int32 _CabinetCount;
        partial void OnCabinetCountChanging(global::System.Int32 value);
        partial void OnCabinetCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RackCount
        {
            get
            {
                return _RackCount;
            }
            set
            {
                if (_RackCount != value)
                {
                    OnRackCountChanging(value);
                    ReportPropertyChanging("RackCount");
                    _RackCount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RackCount");
                    OnRackCountChanged();
                }
            }
        }
        private global::System.Int32 _RackCount;
        partial void OnRackCountChanging(global::System.Int32 value);
        partial void OnRackCountChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SampleRoomModel", Name="SelectShoesImageByArticle_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SelectShoesImageByArticle_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SelectShoesImageByArticle_Result object.
        /// </summary>
        /// <param name="shoesImageId">Initial value of the ShoesImageId property.</param>
        public static SelectShoesImageByArticle_Result CreateSelectShoesImageByArticle_Result(global::System.Int32 shoesImageId)
        {
            SelectShoesImageByArticle_Result selectShoesImageByArticle_Result = new SelectShoesImageByArticle_Result();
            selectShoesImageByArticle_Result.ShoesImageId = shoesImageId;
            return selectShoesImageByArticle_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShoesImageId
        {
            get
            {
                return _ShoesImageId;
            }
            set
            {
                OnShoesImageIdChanging(value);
                ReportPropertyChanging("ShoesImageId");
                _ShoesImageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShoesImageId");
                OnShoesImageIdChanged();
            }
        }
        private global::System.Int32 _ShoesImageId;
        partial void OnShoesImageIdChanging(global::System.Int32 value);
        partial void OnShoesImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Article
        {
            get
            {
                return _Article;
            }
            set
            {
                OnArticleChanging(value);
                ReportPropertyChanging("Article");
                _Article = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Article");
                OnArticleChanged();
            }
        }
        private global::System.String _Article;
        partial void OnArticleChanging(global::System.String value);
        partial void OnArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();

        #endregion

    }

    #endregion

    
}
