//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTesting.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WHLaminationEntities : DbContext
    {
        public WHLaminationEntities()
            : base("name=WHLaminationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LaminationMaterial> LaminationMaterials { get; set; }
    
        public virtual ObjectResult<spm_SelectLaminationMaterialByOrderNo_Result> spm_SelectLaminationMaterialByOrderNo(string orderNo)
        {
            var orderNoParameter = orderNo != null ?
                new ObjectParameter("OrderNo", orderNo) :
                new ObjectParameter("OrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spm_SelectLaminationMaterialByOrderNo_Result>("spm_SelectLaminationMaterialByOrderNo", orderNoParameter);
        }
    }
}
